import express from "express";
import "dotenv/config";

const app = express();
const PORT = process.env.PORT || 3000;
const HA_URL = process.env.HOME_ASSISTANT_URL || "http://homeassistant:8123";
const HA_TOKEN = process.env.HOME_ASSISTANT_TOKEN;

app.get("/health", (_req, res) => res.json({ status: "ok" }));

// Aggregated payload the frontend polls. Each source is fetched independently
// so one flaky integration (looking at you, MyQ) doesn't take down the rest.
app.get("/api/dashboard", async (_req, res) => {
  const [weather, calendar, homeAssistant] = await Promise.allSettled([
    getWeather(),
    getCalendar(),
    getHomeAssistantStates(),
  ]);

  res.json({
    weather: weather.status === "fulfilled" ? weather.value : null,
    calendar: calendar.status === "fulfilled" ? calendar.value : null,
    homeAssistant: homeAssistant.status === "fulfilled" ? homeAssistant.value : null,
    errors: [weather, calendar, homeAssistant]
      .filter((r) => r.status === "rejected")
      .map((r) => r.reason?.message || "unknown error"),
  });
});

async function getWeather() {
  // Open-Meteo needs no API key - good default for a LAN-only dashboard.
  const lat = process.env.LAT;
  const lon = process.env.LON;
  const url = `https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,weather_code&daily=temperature_2m_max,temperature_2m_min&temperature_unit=fahrenheit`;
  const r = await fetch(url);
  if (!r.ok) throw new Error(`weather fetch failed: ${r.status}`);
  return r.json();
}

async function getCalendar() {
  // TODO: wire up googleapis Calendar client using the refresh token
  // generated by auth/get-refresh-token.js
  throw new Error("calendar integration not yet configured");
}

async function getHomeAssistantStates() {
  const r = await fetch(`${HA_URL}/api/states`, {
    headers: { Authorization: `Bearer ${HA_TOKEN}` },
  });
  if (!r.ok) throw new Error(`Home Assistant fetch failed: ${r.status}`);
  return r.json();
}

app.listen(PORT, () => console.log(`Backend listening on :${PORT}`));
